### ISSUE TITLE
Content filter by category does not work

### ISSUE THREAD

**Issue by exaline-ru** [MaviTm/estate#2]
Content filter by category does not work. All page templates are customized as in: oc_estate/example/themePages/, So how on page: https://octobercms.com/plugin/mavitm-estate.
What are the possible reasons? (js, css...!?)

**Comment by mavitm** [comment]
Can you share page codes in your theme?

**Comment by exaline-ru** [comment]
Too long code. I'll write to the mail.

**Comment by mavitm** [comment]
thanks for the feedback I posted a new update

**Comment by exaline-ru** [comment]
Error after update:
![image](https://user-images.githubusercontent.com/46493161/60724437-1a080500-9f3f-11e9-87e0-ed15f2264011.png)

**Comment by exaline-ru** [comment]
Correction:

<div class="col-md-3 col-xs-6">
            <input type="number" name="price[]" class="form-control" placeholder="{{ 'Min price'|_ }}">
        </div>

        <div class="col-md-3 col-xs-6">
            <input type="number" name="price[]" class="form-control" placeholder="{{ 'Max price'|_ }}">
        </div>

**Comment by mavitm** [comment]
Released a new update for translation error and search

**Comment by exaline-ru** [comment]
Update failed

"A syntax error was detected in /home/admin/web/domain.com/public_html/plugins/vdlp/redirect/updates/version.yaml. Unable to parse at line 35 (near " - 20190704_0007_add_timestamp_crawler_index_on_clients_table.php") at line 38 (near "/home/admin/web/domain.com/public_html/vendor/october/rain/src/Parse/Yaml.php")." on line 38 of /home/admin/web/domain.com/public_html/vendor/october/rain/src/Parse/Yaml.php

**Comment by mavitm** [comment]
I removed it a few times and set it up again, I couldn't see any problems. "20190704_0007_add_timestamp_crawler_index_on_clients_table.php"  find this file in your own project, may be another plugin

**Comment by exaline-ru** [comment]
Checked: conflict when updating with redirect plugin. Temporarily disabled this plugin and update your plugin successfully passed. But even after the update, the Cyrillic tags are not saved. Error: "Tags may only contain alpha-numeric characters and hyphens".

**Comment by mavitm** [comment]
Yes, I have applied a process for verification. I'll send a new update for
a short time

exaline-ru <notifications@github.com>, 8 Tem 2019 Pzt, 14:28 tarihinde şunu
yazdı:

**Comment by mavitm** [comment]
ok new version released

Ayhan ERASLAN <ayer50@gmail.com>, 8 Tem 2019 Pzt, 16:11 tarihinde şunu
yazdı:

**Comment by exaline-ru** [comment]
Thank you very much! Now working and search and Cyrillic. If possible - finish the card function, please! For real estate is a necessity.

**Comment by mavitm** [comment]
Exactly what do you mean by "card function"

exaline-ru <notifications@github.com>, 8 Tem 2019 Pzt, 21:18 tarihinde şunu
yazdı:

**Comment by exaline-ru** [comment]
Sorry for bad english! I mean: add a map to the object.

**Comment by mavitm** [comment]
No problem my English is bad, is there an example for this?

exaline-ru <notifications@github.com>, 8 Tem 2019 Pzt, 22:13 tarihinde şunu
yazdı:

**Comment by exaline-ru** [comment]
For example: Leaflet Maps
Displays beautiful maps with custom overlays, markers and objects | https://octobercms.com/plugin/timfoerster-leaflet

**Comment by mavitm** [comment]
sorry I can't promise that, I don't have much free time

exaline-ru <notifications@github.com>, 8 Tem 2019 Pzt, 22:50 tarihinde şunu
yazdı:

**Comment by exaline-ru** [comment]
As much as you can, of course. Only if there is such a feature, then your plugin will become more in demand.

**Comment by daavids** [comment]
@exaline-ru Feel free to fork the project and make those changes yourself. You can always make a pull request after to have your changes added to this repo.
