### ISSUE TITLE
Price filtering in search form doesn't work when min price is set at 0.

### ISSUE THREAD

**Issue by daavids** [MaviTm/estate#4]
Since PHP's empty() evaluates 0 as empty, the whereBetween clause (line 208 in models\Realty.php) never gets added.

For example, if I wanted to find all properties with a price between 0 and 100,000, it would find also find properties that are priced above 100,000, since the filter doesn't apply.

Also  you might want to replace the price input array with a min_price and max_price, since when inputting just one price, it always assumes it's the min price.

P.S. The price filter worked just fine before the last update.

**Comment by mavitm** [comment]
Hi
I've reviewed your pull request, which is much better than I wrote, and
I'll add a new update soon
thanks

Davids <notifications@github.com>, 8 Tem 2019 Pzt, 23:36 tarihinde şunu
yazdı:
