### ISSUE TITLE
Error in creating because of the long text (excerpt)

### ISSUE THREAD

**Issue by exaline-ru** [MaviTm/estate#6]
Error in creating because of the long text:
"SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'excerpt' at row 1 (SQL: insert into `mavitm_estate_realty` (`user_id`, `title`, `excerpt`, `description`, `slug`, `category_id`, `price`, `status`, `published`, `updated_at`, `created_at`) values (...

**Comment by mavitm** [comment]
"excerpt" field can only contain 255 characters, short input text

exaline-ru <notifications@github.com>, 9 Tem 2019 Sal, 14:46 tarihinde şunu
yazdı:
