### ISSUE TITLE
How to properly sort the content?

### ISSUE THREAD

**Issue by exaline-ru** [MaviTm/estate#8]
Currently using this code (by update). But it does not work.

`function onStart() { 
    $this['items'] = \Mavitm\Estate\Models\Realty::where('published', '=', '1')->orderby('updated_at', 'desc')->get();
}`

**Comment by daavids** [comment]
The order method is [orderBy](https://octobercms.com/docs/database/model#adding-constraints) not orderby.

**Comment by exaline-ru** [comment]
Is it possible to add sorting in the component !? Now there is no sorting.

**Comment by daavids** [comment]
I might add it later this week. No promises though.

**Comment by mavitm** [comment]
Hi 
I added options to the list component for sorting
